### ISSUE TITLE
connection reset

### ISSUE THREAD

**Issue by functionlinx** [leavesC/WifiFileTransfer#1]
@leavesC   您好
客户端出现socketexception：connection reset
在 outputStream.write(buf, 0, len); 这里出错。
不知道为什么，服务端并没有socket.close

**Comment by leavesC** [comment]
这种问题不好分析啊，打断点调试下服务器是否有启动了接收线程

**Comment by functionlinx** [comment]
> 这种问题不好分析啊，打断点调试下服务器是否有启动了接收线程

我用手机去和嵌入式进行wifi连接出现connection reset，换成两台手机连接成功了。不过两台手机上的app得是同一个名字，不然app1.filetransfer和app2.filetransfer不一样就会出错。

**Comment by leavesC** [comment]
> > 这种问题不好分析啊，打断点调试下服务器是否有启动了接收线程
> 
> 我用手机去和嵌入式进行wifi连接出现connection reset，换成两台手机连接成功了。不过两台手机上的app得是同一个名字，不然app1.filetransfer和app2.filetransfer不一样就会出错。

不需要同个名字，只要appid不一样就可以的
