### ISSUE TITLE
当前连接的SSID并非文件接收端开启的WIFI热点

### ISSUE THREAD

**Issue by sonichy** [leavesC/WifiFileTransfer#2]
1.已连接热点，显示非连接
```
Log.e(Thread.currentThread().getStackTrace()[2] + "", WifiLManager.getConnectedSSID(this)); //奇怪了，日志不显示
showToast("当前连接的" + WifiLManager.getConnectedSSID(this) + "并非文件接收端开启的WIFI热点，请重试"); //改一下，显示在Toast中，结果是 unknown ssid。
//return; 注销return跑下面的代码成功发送和接收
```
#### Android 9.0 及以上的机型，必须打开位置权限的总开关，并且请求定位权限，才可以正确获取到WIFI名称
AndroidMainifest.xml添加：
```<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>```
checkPermission(View view) 添加
```Manifest.permission.ACCESS_FINE_LOCATION```
#### TextView显示SSID：
```tv_hint.setText("发送文件前需要先连上文件接收端的WIFI热点。\n当前热点：" + WifiLManager.getConnectedSSID(this));```

2.检查权限代码优化：显示具体哪个权限没授权
```
@Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == CODE_REQ_PERMISSIONS) {
            for (int i=0; i<grantResults.length; i++) {
                if (grantResults[i] != PackageManager.PERMISSION_GRANTED) {
                    showToast(permissions[i] + "缺少权限，请先授予权限");
                    return;
                } else {
                    //showToast("已获得权限");
                }
                showToast("已获得所需全部权限");
            }
        }
    }
```

3.收到文件后需要刷新媒体库：
`MediaScannerConnection.scanFile(MainActivity.this, new String[] { path }, null, null);`

4.固定SSID和密码是没有必要的

5.发送应用

5.第三方文件选择没有必要，而且没有视频分类

**Comment by leavesC** [comment]
你好，感谢你的反馈哈。为了方便实现，有些细节我的确是写得比较粗糙 😂😂想要引用的话的确需要再进行优化才行
